/**
 * scripts/lib/prompts/export.ts
 *
 * Exported prompts are written as Obsidian-flavored markdown laid out for
 * copy-paste (the prompt body lives in a fenced code block so the editor's copy
 * button grabs it clean). Notes render fine in any markdown reader — Obsidian
 * just gets the nicer callouts.
 *
 * Destination: ./exported-prompts by default. Point MACRO_PICKLE_PROMPT_VAULT at
 * a notes vault (Obsidian, Logseq, a plain folder) to collect them there instead.
 */

import fs from "fs";
import path from "path";
import { slugify, timestamp } from "../imagen.js";

export const VAULT_PROMPTS_DIR =
  process.env.MACRO_PICKLE_PROMPT_VAULT || "exported-prompts";

/**
 * Optional: collapse a family of related brand slugs under one hub folder
 * instead of spraying sibling folders across the destination. Maps a brand slug
 * → the relative sub-path it should export into. Extend for your own brands.
 */
const BRAND_FOLDER: Record<string, string> = {};

export interface ExportOptions {
  kind: "image" | "video";
  title: string;
  /** The built, copy-paste-ready prompt body. */
  prompt: string;
  brand?: string;
  aspect?: string;
  /** Target tool, e.g. "Imagen 4.0" or "Veo 3.1 / Google Flow". */
  tool?: string;
  /** Source brief, embedded for reproducibility. */
  brief?: unknown;
}

function isoDate(): string {
  const d = new Date();
  const p = (n: number) => String(n).padStart(2, "0");
  return `${d.getFullYear()}-${p(d.getMonth() + 1)}-${p(d.getDate())}`;
}

function renderNote(opts: ExportOptions): string {
  const tool =
    opts.tool ?? (opts.kind === "video" ? "Veo 3.1 / Google Flow" : "Imagen 4.0 / Nano Banana Pro");
  const tags = ["prompt", "macro-pickle", opts.kind];
  if (opts.brand) tags.push(opts.brand.toLowerCase());

  const fm = [
    "---",
    `title: ${opts.title}`,
    "type: ai-prompt",
    `kind: ${opts.kind}`,
    ...(opts.brand ? [`brand: ${opts.brand}`] : []),
    `tool: ${tool}`,
    ...(opts.aspect ? [`aspect: "${opts.aspect}"`] : []),
    `created: ${isoDate()}`,
    "tags:",
    ...tags.map((t) => `  - ${t}`),
    "---",
  ].join("\n");

  const body = [
    "",
    `# ${opts.title}`,
    "",
    "> [!tip] Copy-paste prompt",
    `> Paste the block below straight into **${tool}**.`,
    "",
    "```text",
    opts.prompt.trim(),
    "```",
  ];

  if (opts.brief !== undefined) {
    body.push(
      "",
      "> [!example]- Source brief (reproducible)",
      "> ```json",
      ...JSON.stringify(opts.brief, null, 2)
        .split("\n")
        .map((l) => `> ${l}`),
      "> ```"
    );
  }

  body.push(
    "",
    "---",
    "> [!note] Generated by the macro-pickle Prompt Engine. Methodology: `content/knowledge/PROMPT-COOKBOOK.md`."
  );

  return fm + "\n" + body.join("\n") + "\n";
}

/** Write the prompt note into the vault. Returns the absolute file path. */
export function exportPromptToVault(opts: ExportOptions): string {
  const slug = opts.brand ? opts.brand.toLowerCase() : "";
  const brandSeg = BRAND_FOLDER[slug] ?? slug;
  const dir = path.join(VAULT_PROMPTS_DIR, brandSeg);
  fs.mkdirSync(dir, { recursive: true });
  // slugify truncates to 40 chars and timestamp() is second-precision, so several
  // notes exported in the same second (e.g. a pack's hero+still+spot) can collide on
  // one filename and silently overwrite each other. Guard with a -2/-3 suffix.
  const base = `${slugify(opts.title)}-${timestamp()}`;
  let file = path.join(dir, `${base}.md`);
  for (let n = 2; fs.existsSync(file); n++) file = path.join(dir, `${base}-${n}.md`);
  fs.writeFileSync(file, renderNote(opts), "utf-8");
  return file;
}
